### ISSUE TITLE
set_qos function problem

### ISSUE THREAD

**Issue by joe820912boy** [faucetsdn/ryu#114]
My problem is that if I want to set up the queues on port "eth1" of switch "s1"  
https://sourceforge.net/p/ryu/mailman/message/36150616/

The difference of my code is that mine config_path is controller_ip "tcp:127.0.0.1:6653"

I have saw the use of "set_qos" on it. But when I compile my ryu.py it occurs different error in the following.

**Invalid or incomplete multibyte or wide character
SimpleSwitch13: Exception occurred during handler processing. Backtrace from offending handler [switch_features_handler] servicing event [EventOFPSwitchFeatures] follows.
Traceback (most recent call last):
  File "/home/sdn/.local/lib/python3.5/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/sdn/ryu/ryu/app/loadbalancer.py", line 80, in switch_features_handler
    ovs_bridge.set_qos("eth1", type='linux-htb', max_rate="1000000", queues=[{'min-rate':'10000', 'max-rate':'100000'}])
  File "/home/sdn/.local/lib/python3.5/site-packages/ryu/lib/ovs/bridge.py", line 536, in set_qos
    self.run_command([command_qos, command_queue])
  File "/home/sdn/.local/lib/python3.5/site-packages/ryu/lib/ovs/bridge.py", line 137, in run_command
    self.vsctl.run_command(commands, self.timeout, self.exception)
  File "/home/sdn/.local/lib/python3.5/site-packages/ryu/lib/ovs/vsctl.py", line 1295, in run_command
    self._run_command(commands)
  File "/home/sdn/.local/lib/python3.5/site-packages/ryu/lib/ovs/vsctl.py", line 1275, in _run_command
    self._do_main(commands)
  File "/home/sdn/.local/lib/python3.5/site-packages/ryu/lib/ovs/vsctl.py", line 1172, in _do_main
    self._init_schema_helper()
  File "/home/sdn/.local/lib/python3.5/site-packages/ryu/lib/ovs/vsctl.py", line 1059, in _init_schema_helper
    vswitch_idl.OVSREC_DB_NAME)
  File "/home/sdn/.local/lib/python3.5/site-packages/ryu/lib/ovs/vsctl.py", line 1051, in _rpc_get_schema_json
    vsctl_fatal(os.strerror(error))
  File "/home/sdn/.local/lib/python3.5/site-packages/ryu/lib/ovs/vsctl.py", line 180, in vsctl_fatal
    raise Exception(msg)        # not call ovs.utils.ovs_fatal for reusability
Exception: Invalid or incomplete multibyte or wide character**

This typeerror I google for it that I get some solution is encoding with my code.
I have checked that my encoding is UTF-8 or ASCII, so I think that may not be the problem I found.

If someone has met this problem plz let me know it, thanks!!

**Comment by joe820912boy** [comment]
My environment version of ryu is 4.34, mininet is 2.3.0d6, ovs-vsctl (Open vSwitch) 2.12.0 DB Schema 8.0.0

**Comment by joe820912boy** [comment]
I have solve this problem!!!
The main error occurs on config_path. 
Its setting port needs the same port which you set the ovsdb port, e.g sudo ovs-vsctl set-manager ptcp:6640
which config_path's port need to be 6640, not the controller port..
